-- ================================================
-- Healthcare Admin AI - Supabase PostgreSQL Schema
-- Run this in your Supabase SQL Editor
-- ================================================

-- 1. Create records table
CREATE TABLE IF NOT EXISTS records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    form_type TEXT NOT NULL,
    filename TEXT,
    user_email TEXT NOT NULL DEFAULT 'dr.smith@health.ai',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fields_json TEXT NOT NULL DEFAULT '{}',
    total_fields INT NOT NULL DEFAULT 0,
    missing_fields INT NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'pending_review',
    draft_text TEXT,
    file_path TEXT,
    notification_sent INT NOT NULL DEFAULT 0
);

-- 2. Create users table
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'user',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. Create notifications table
CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_id BIGINT NOT NULL,
    recipient_email TEXT NOT NULL,
    link TEXT NOT NULL,
    sent_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 4. Enable Row Level Security (RLS) or public access policies
ALTER TABLE records ENABLE ROW LEVEL SECURITY;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;

-- Create basic access policies for anon / service role access
CREATE POLICY "Allow public read/write access to records" ON records FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read/write access to users" ON users FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read/write access to notifications" ON notifications FOR ALL USING (true) WITH CHECK (true);

-- 5. Seed default demo accounts
-- Passwords:
-- Admin: admin1234 -> SHA256: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
-- Doctor: demo1234  -> SHA256: e80b5017098950fc58aad83c8c14978e2ed489c200424564c7f07827878d6b9d
INSERT INTO users (full_name, email, password_hash, role)
VALUES 
  ('System Admin', 'admin@health.ai', '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918', 'admin'),
  ('Dr. Smith', 'dr.smith@health.ai', 'e80b5017098950fc58aad83c8c14978e2ed489c200424564c7f07827878d6b9d', 'user')
ON CONFLICT (email) DO NOTHING;
